// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { getDatabaseUrl } from "./src/prisma/database-url.js";

// `prisma generate` doesn't need a URL, so don't fail when DB vars are absent (e.g. during docker build)
function tryGetDatabaseUrl() {
  try {
    return getDatabaseUrl();
  } catch {
    return undefined;
  }
}

export default defineConfig({
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: tryGetDatabaseUrl(),
  },
});
